# -*- coding: utf-8 -*-
"""Reto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZVDUl8rj6trp3hNlrVPFhY-88rD7k8hA
"""

guia = input ()
jugador1 = input()
jugador2 = input()
i=0
while(i<10):
  if(guia[i] == "🃏"):
    print("🛸", end="")
  else:
    if(jugador1[i] == "🃏" and jugador2[i] == "🃏"):
      print("🤩", end="")
    elif(jugador1[i] == "🃁" and jugador2[i] == "🃁" and guia[i] != "🃁"):
      print("🤬", end="")
    elif(jugador1[i]<=guia[i] and jugador2[i]<=guia[i]):
      print("🛸", end="")
    elif(jugador1[i] == jugador2[i]):
      print("🛸", end="")
    elif(jugador1[i]<jugador2[i]):
      print("🤡", end="")
    elif(jugador1[i]>jugador2[i]):
      print("🤖", end="")  
  i+=1